; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient
  bodmer/TFT_eSPI

build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=-1
  -D TFT_DC=2
  -D TFT_RST=4
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D SPI_FREQUENCY=20000000